### ISSUE TITLE
I can't get this

### ISSUE THREAD

**Issue by Rom3k90** [XternA/income-generator#50]
`C:\Windows\system32>igm

sh: git: not found
sh: igm: not found`

When I try to run after the first setup by typing igm into the command line only this displays what I see at the top

**Comment by XternA** [comment]
Your system doesn't have `git` installed. 

Run this command: `winget install -i Git.Git`.

If you're on latest version of Windows 10 and 11 then there should be the Windows Package Manager `Winget` and that command there should install `git` directly for you.

If it fails, then download and install manually from here: https://git-scm.com/downloads.

I do strongly recommend you read through the wiki and any instructions given.

**Comment by XternA** [comment]
I've pushed a new update. You can just download the updated Windows script and run it with the command below.

```
curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat
```

Again, this will assume your system has `winget`.

**Comment by Rom3k90** [comment]
`C:\Users\lolek\Desktop>git -v
git version 2.47.0.windows.2

C:\Users\lolek\Desktop>igm

sh: git: not found
sh: igm: not found

C:\Users\lolek\Desktop>`

I installed git and ran the installation but it's still the same

**Comment by Rom3k90** [comment]
1. C:\Users\lolek\AppData\Local\Microsoft\WindowsApps\winget.exe
2. PRETTY_NAME="Docker Desktop" , strange though I installed ubuntu
3. C:\Users\lolek>wsl which git
C:\Users\lolek>
4. C:\Users\lolek>dir /b %appdata%\IGM
igm.bat

C:\Users\lolek>

**Comment by XternA** [comment]
From the looks of it. it seems like the issue is with your WSL. Everything else seems to be in the right place.

The fact `wsl cat /etc/os-release` didn't return a Linux disto but instead "Docker Desktop" tells me the following:

1. You've got Docker Desktop installed but not actually "Ubuntu" under WSL.
2. You probably actually don't have any Linux distro installed which is why `wsl git` didn't return the path.

Please do the following:

1. Please remove the Docker desktop first to ensure what we do next won't interfere with what we're going to do next.
2. Run all these steps below:
```
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart

wsl --set-default-version 2
wsl --update
wsl --install -d Ubuntu

# Run this to confirm you switch over to WSL
wsl

cat /etc/os-release
```
3. If all correct it should now show Ubuntu as the distro.
4. If it does indeed show Ubuntu, then you can close the terminal and start a new one again.
5. Type `igm` again, which should work now. Then proceed to `Option 7` and install docker from the menu again and refer to the Docker Desktop UI section for a few changes: https://github.com/XternA/income-generator/wiki/Docker-Installation#windows

Thanks for your patience.
